[package]
name = "tauri-wasm"
description = "Tauri API in WASM"
documentation = "https://docs.rs/tauri-wasm"
readme = "README.md"
license = "MIT"
authors = ["nanoqsh"]
repository = "https://github.com/nanoqsh/tauri-wasm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
wasm-bindgen.workspace = true
