[package]
name = "app"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
gloo = { workspace = true, features = ["console"] }
tauri-wasm.workspace = true
wasm-bindgen.workspace = true
