name: ci
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
env:
    CARGO_INCREMENTAL: false
    CARGO_TERM_COLOR: always
    RUSTFLAGS: -Dwarnings
    RUST_BACKTRACE: full
    MSRV: 1.85
    RUSTDOCFLAGS: -Dwarnings
    CACHE_SUFFIX: c
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Build
            run: cargo build --verbose -p tauri-wasm --all-features
          - name: Clippy
            run: cargo clippy -p tauri-wasm --all-features
          - name: Tests
            run: cargo test --verbose -p tauri-wasm --all-features
